apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassName }}
provisioner: ebs.csi.aws.com
volumeBindingMode: {{ .Values.volumeBindingMode }}
parameters:
  csi.storage.k8s.io/fstype: {{ .Values.fsType }}
  type: {{ .Values.volumeType }}
  iopsPerGB: "{{ .Values.storageClassIopsPerGB }}"
  encrypted: "{{ .Values.storageClassEncryption }}"
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    {{- range .Values.storageClassValidZones }}
    - {{ . }}
    {{- end }}