app:
  name: app
  env:
    - name: SERVER_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
deployment:
  name: app
  image: 211125571131.dkr.ecr.us-east-1.amazonaws.com/eks-service-app-ecr:latest
  containerPort: 8080
  replicas: 1
  limits:
    memory: "128Mi"
    cpu: "100m"
  imagePullPolicy: "Always"
service:
  name: app-service
  port: 80
  targetPort: 8080
  type: NodePort